
linters:
  enable-all: true
  disable:
    - exportloopref # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - dupl
    - wsl
    - nlreturn
    - mnd
    - err113
    - errname # Require a breaking change.
    - wrapcheck
    - exhaustive
    - exhaustruct
    - testpackage
    - tparallel
    - paralleltest
    - prealloc
    - forcetypeassert
    - noctx

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 40
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
    settings:
      hugeParam:
        sizeThreshold: 100

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "ST1000:"
    - "`(methodDomainGetRules|methodDomainLog|methodDomainPush|methodDomainRenew|methodDomainRestore|methodDomainStats|methodDomainTrade|methodDomainTransfer|methodDomainTransferOut|methodDomainUpdate)` is unused"
    - "`(methodNameserverUpdate|methodNameserverDelete)` is unused"
    - "package-comments: should have a package comment"
  exclude-rules:
    - path: .*_test.go
      linters:
        - funlen
        - bodyclose
    - path: response.go # errname
      text: 'the type name `ErrorResponse` should conform to the `XxxError` format'

output:
  show-stats: true
  sort-results: true
  sort-order:
    - linter
    - file

run:
  timeout: 5m
